/**
 * Restaurant menu database with macro data
 * Expanded: 18 restaurants, 400+ menu items
 * Each item: { name, calories, protein, carbs, fat }
 */
export const RESTAURANT_MENUS = {
  chipotle: [
    { name: 'Chicken Burrito Bowl', calories: 625, protein: 51, carbs: 64, fat: 16 },
    { name: 'Steak Burrito Bowl', calories: 595, protein: 47, carbs: 64, fat: 15 },
    { name: 'Barbacoa Burrito Bowl', calories: 570, protein: 43, carbs: 64, fat: 14 },
    { name: 'Chicken Salad Bowl', calories: 430, protein: 47, carbs: 25, fat: 14 },
    { name: 'Steak Salad Bowl', calories: 405, protein: 43, carbs: 25, fat: 13 },
    { name: 'Chicken Tacos (3)', calories: 525, protein: 42, carbs: 54, fat: 14 },
    { name: 'Steak Tacos (3)', calories: 495, protein: 38, carbs: 54, fat: 13 },
    { name: 'Sofritas Bowl', calories: 545, protein: 22, carbs: 72, fat: 20 },
    { name: 'Carnitas Burrito', calories: 945, protein: 45, carbs: 100, fat: 38 },
    { name: 'Chicken Quesadilla', calories: 740, protein: 48, carbs: 50, fat: 38 },
    { name: 'Veggie Bowl', calories: 480, protein: 15, carbs: 72, fat: 18 },
    { name: 'Chicken Burrito', calories: 855, protein: 51, carbs: 100, fat: 28 },
    { name: 'Lifestyle Bowl - Paleo', calories: 445, protein: 47, carbs: 20, fat: 22 },
    { name: 'Lifestyle Bowl - Wholesome', calories: 510, protein: 41, carbs: 55, fat: 18 },
    { name: 'Chicken Protein Bowl (no rice/beans)', calories: 325, protein: 51, carbs: 12, fat: 10 },
    { name: 'Kids Chicken Quesadilla', calories: 380, protein: 24, carbs: 28, fat: 18 },
    { name: 'Guacamole (side)', calories: 230, protein: 3, carbs: 13, fat: 22 },
    { name: 'Chips & Guac', calories: 770, protein: 9, carbs: 88, fat: 44 },
  ],
  mcdonalds: [
    { name: 'Grilled Chicken Sandwich', calories: 400, protein: 37, carbs: 44, fat: 10 },
    { name: 'McChicken', calories: 400, protein: 14, carbs: 39, fat: 21 },
    { name: 'Quarter Pounder w/ Cheese', calories: 520, protein: 30, carbs: 42, fat: 26 },
    { name: 'Big Mac', calories: 550, protein: 25, carbs: 45, fat: 30 },
    { name: 'Egg McMuffin', calories: 300, protein: 17, carbs: 30, fat: 13 },
    { name: 'Filet-O-Fish', calories: 390, protein: 16, carbs: 39, fat: 19 },
    { name: 'Southwest Grilled Chicken Salad', calories: 350, protein: 37, carbs: 27, fat: 11 },
    { name: '6pc Chicken McNuggets', calories: 250, protein: 15, carbs: 15, fat: 15 },
    { name: 'Fruit & Yogurt Parfait', calories: 150, protein: 4, carbs: 30, fat: 2 },
    { name: 'Sausage Burrito', calories: 310, protein: 12, carbs: 26, fat: 17 },
    { name: 'McDouble', calories: 390, protein: 22, carbs: 33, fat: 19 },
    { name: 'Bacon Egg & Cheese Biscuit', calories: 460, protein: 19, carbs: 40, fat: 24 },
    { name: 'Artisan Grilled Chicken Sandwich', calories: 360, protein: 37, carbs: 44, fat: 6 },
    { name: 'Side Salad (no dressing)', calories: 15, protein: 1, carbs: 3, fat: 0 },
    { name: 'Apple Slices', calories: 15, protein: 0, carbs: 4, fat: 0 },
    { name: 'Oatmeal (fruit & maple)', calories: 310, protein: 5, carbs: 64, fat: 4 },
  ],
  subway: [
    { name: 'Turkey Breast 6" Sub', calories: 280, protein: 18, carbs: 46, fat: 3.5 },
    { name: 'Chicken Breast 6" Sub', calories: 320, protein: 25, carbs: 47, fat: 5 },
    { name: 'Veggie Delite 6" Sub', calories: 230, protein: 8, carbs: 44, fat: 2.5 },
    { name: 'Steak & Cheese 6" Sub', calories: 380, protein: 26, carbs: 48, fat: 10 },
    { name: 'Tuna 6" Sub', calories: 480, protein: 20, carbs: 44, fat: 25 },
    { name: 'Italian BMT 6" Sub', calories: 410, protein: 20, carbs: 46, fat: 16 },
    { name: 'Rotisserie Chicken 6" Sub', calories: 320, protein: 28, carbs: 44, fat: 5 },
    { name: 'Protein Bowl - Chicken', calories: 220, protein: 26, carbs: 12, fat: 6 },
    { name: 'Protein Bowl - Steak', calories: 250, protein: 24, carbs: 14, fat: 10 },
    { name: 'Chopped Salad - Turkey', calories: 180, protein: 18, carbs: 12, fat: 4 },
    { name: 'Turkey 12" Sub', calories: 560, protein: 36, carbs: 92, fat: 7 },
    { name: 'Egg & Cheese 6" Breakfast', calories: 370, protein: 17, carbs: 46, fat: 13 },
    { name: 'Black Forest Ham 6"', calories: 290, protein: 18, carbs: 47, fat: 4.5 },
    { name: 'Sweet Onion Chicken Teriyaki 6"', calories: 370, protein: 26, carbs: 54, fat: 5 },
    { name: 'Meatball Marinara 6"', calories: 480, protein: 21, carbs: 64, fat: 17 },
    { name: 'Veggie Delite Salad', calories: 60, protein: 3, carbs: 11, fat: 0.5 },
  ],
  chickfila: [
    { name: 'Grilled Chicken Sandwich', calories: 390, protein: 38, carbs: 42, fat: 12 },
    { name: 'Grilled Nuggets (12ct)', calories: 200, protein: 38, carbs: 2, fat: 4 },
    { name: 'Chicken Sandwich', calories: 440, protein: 28, carbs: 40, fat: 19 },
    { name: 'Spicy Chicken Sandwich', calories: 450, protein: 28, carbs: 42, fat: 19 },
    { name: 'Grilled Cool Wrap', calories: 350, protein: 37, carbs: 30, fat: 13 },
    { name: 'Cobb Salad w/ Grilled Nuggets', calories: 510, protein: 44, carbs: 28, fat: 27 },
    { name: 'Market Salad w/ Grilled Nuggets', calories: 450, protein: 40, carbs: 32, fat: 20 },
    { name: 'Egg White Grill', calories: 300, protein: 26, carbs: 31, fat: 7 },
    { name: 'Grilled Chicken Club', calories: 520, protein: 44, carbs: 43, fat: 18 },
    { name: 'Greek Yogurt Parfait', calories: 270, protein: 12, carbs: 44, fat: 6 },
    { name: 'Hash Browns', calories: 260, protein: 2, carbs: 26, fat: 17 },
    { name: 'Grilled Nuggets (8ct)', calories: 130, protein: 25, carbs: 1, fat: 3 },
    { name: 'Chicken Nuggets (8ct)', calories: 260, protein: 22, carbs: 14, fat: 13 },
    { name: 'Side Salad', calories: 80, protein: 5, carbs: 9, fat: 5 },
    { name: 'Fruit Cup', calories: 70, protein: 1, carbs: 17, fat: 0 },
    { name: 'Waffle Fries (small)', calories: 310, protein: 4, carbs: 40, fat: 16 },
  ],
  sweetgreen: [
    { name: 'Harvest Bowl', calories: 705, protein: 25, carbs: 62, fat: 42 },
    { name: 'Kale Caesar', calories: 490, protein: 35, carbs: 28, fat: 30 },
    { name: 'Chicken Pesto Parm', calories: 620, protein: 40, carbs: 48, fat: 32 },
    { name: 'Super Green Goddess', calories: 480, protein: 28, carbs: 42, fat: 22 },
    { name: 'Buffalo Chicken Bowl', calories: 545, protein: 38, carbs: 45, fat: 24 },
    { name: 'Shroomami', calories: 580, protein: 18, carbs: 68, fat: 28 },
    { name: 'Crispy Rice Bowl', calories: 650, protein: 22, carbs: 74, fat: 32 },
    { name: 'Guacamole Greens', calories: 520, protein: 24, carbs: 38, fat: 34 },
    { name: 'Grilled Chicken (add-on)', calories: 155, protein: 30, carbs: 0, fat: 4 },
    { name: 'Roasted Chicken (add-on)', calories: 135, protein: 24, carbs: 1, fat: 4 },
    { name: 'Build Your Own - Base Salad', calories: 250, protein: 8, carbs: 32, fat: 12 },
    { name: 'Greek Bowl', calories: 590, protein: 32, carbs: 54, fat: 28 },
  ],
  panera: [
    { name: 'Fuji Apple Chicken Salad (full)', calories: 540, protein: 31, carbs: 52, fat: 22 },
    { name: 'Green Goddess Salad w/ Chicken', calories: 520, protein: 38, carbs: 28, fat: 28 },
    { name: 'Turkey Chili', calories: 210, protein: 22, carbs: 28, fat: 4 },
    { name: 'Ten Vegetable Soup', calories: 110, protein: 4, carbs: 22, fat: 2 },
    { name: 'Steel Cut Oatmeal', calories: 290, protein: 8, carbs: 56, fat: 5 },
    { name: 'Avocado Egg White & Spinach', calories: 490, protein: 23, carbs: 64, fat: 13 },
    { name: 'Turkey Sandwich (half)', calories: 340, protein: 21, carbs: 42, fat: 9 },
    { name: 'Chicken Noodle Soup', calories: 110, protein: 8, carbs: 16, fat: 2 },
    { name: 'Greek Salad (full)', calories: 380, protein: 12, carbs: 22, fat: 28 },
    { name: 'Roasted Turkey & Avocado BLT', calories: 690, protein: 40, carbs: 68, fat: 28 },
    { name: 'Lemon Orzo w/ Chicken Soup', calories: 160, protein: 12, carbs: 22, fat: 3 },
    { name: 'Egg & Cheese Breakfast Sandwich', calories: 390, protein: 18, carbs: 46, fat: 14 },
  ],
  shakeshack: [
    { name: 'ShackBurger (single)', calories: 490, protein: 26, carbs: 40, fat: 24 },
    { name: 'SmokeShack (single)', calories: 540, protein: 30, carbs: 40, fat: 28 },
    { name: 'Chicken Shack', calories: 590, protein: 35, carbs: 53, fat: 26 },
    { name: 'Grilled Chicken Sandwich', calories: 440, protein: 40, carbs: 42, fat: 14 },
    { name: 'Shack Stack', calories: 770, protein: 37, carbs: 45, fat: 46 },
    { name: 'Cheeseburger (single)', calories: 450, protein: 24, carbs: 29, fat: 27 },
    { name: 'Veggie Shack', calories: 490, protein: 16, carbs: 58, fat: 22 },
    { name: 'Cheese Fries', calories: 480, protein: 12, carbs: 56, fat: 24 },
    { name: 'Crinkle Cut Fries', calories: 420, protein: 4, carbs: 56, fat: 20 },
    { name: 'Shack-cago Dog', calories: 300, protein: 12, carbs: 28, fat: 16 },
  ],
  starbucks: [
    { name: 'Grilled Chicken Protein Box', calories: 470, protein: 35, carbs: 48, fat: 14 },
    { name: 'Egg & Cheddar Protein Box', calories: 460, protein: 22, carbs: 55, fat: 16 },
    { name: 'Oatmeal (Classic)', calories: 160, protein: 5, carbs: 28, fat: 3 },
    { name: 'Egg White & Roasted Red Pepper Sous Vide', calories: 170, protein: 13, carbs: 18, fat: 4 },
    { name: 'Turkey Bacon & Egg White Sandwich', calories: 230, protein: 17, carbs: 27, fat: 6 },
    { name: 'Spinach Feta Wrap', calories: 290, protein: 20, carbs: 34, fat: 10 },
    { name: 'Chicken & Quinoa Protein Bowl', calories: 420, protein: 27, carbs: 50, fat: 11 },
    { name: 'Cheese & Fruit Protein Box', calories: 380, protein: 14, carbs: 48, fat: 14 },
    { name: 'Tomato Mozzarella Sandwich', calories: 360, protein: 16, carbs: 50, fat: 11 },
    { name: 'Cold Brew (12oz, black)', calories: 5, protein: 0, carbs: 0, fat: 0 },
    { name: 'Nitro Cold Brew (12oz)', calories: 5, protein: 0, carbs: 0, fat: 0 },
    { name: 'Grande Latte (2% milk)', calories: 190, protein: 13, carbs: 19, fat: 7 },
  ],
  cava: [
    { name: 'Chicken & Grains Bowl', calories: 585, protein: 42, carbs: 58, fat: 18 },
    { name: 'Grilled Chicken Salad', calories: 420, protein: 40, carbs: 22, fat: 20 },
    { name: 'Lamb & Beef Meatball Bowl', calories: 620, protein: 36, carbs: 56, fat: 26 },
    { name: 'Harissa Honey Chicken Bowl', calories: 610, protein: 41, carbs: 60, fat: 20 },
    { name: 'Falafel Bowl', calories: 590, protein: 22, carbs: 70, fat: 26 },
    { name: 'Grilled Salmon Bowl', calories: 560, protein: 38, carbs: 48, fat: 22 },
    { name: 'Hummus Bowl', calories: 490, protein: 16, carbs: 62, fat: 22 },
    { name: 'Pita with Tzatziki', calories: 290, protein: 10, carbs: 48, fat: 7 },
    { name: 'Greek Salad Side', calories: 120, protein: 4, carbs: 8, fat: 8 },
    { name: 'SuperGreen Salad Bowl', calories: 445, protein: 36, carbs: 32, fat: 20 },
  ],
  pandaexpress: [
    { name: 'Grilled Teriyaki Chicken (entree)', calories: 300, protein: 36, carbs: 8, fat: 13 },
    { name: 'String Bean Chicken Breast', calories: 190, protein: 14, carbs: 13, fat: 9 },
    { name: 'Broccoli Beef', calories: 150, protein: 10, carbs: 13, fat: 7 },
    { name: 'Mushroom Chicken', calories: 220, protein: 14, carbs: 16, fat: 10 },
    { name: 'SteamRoasted Chicken', calories: 180, protein: 24, carbs: 7, fat: 7 },
    { name: 'Kung Pao Chicken', calories: 290, protein: 16, carbs: 22, fat: 15 },
    { name: 'Orange Chicken', calories: 420, protein: 15, carbs: 46, fat: 21 },
    { name: 'Honey Walnut Shrimp', calories: 360, protein: 13, carbs: 35, fat: 23 },
    { name: 'Chow Mein (side)', calories: 510, protein: 13, carbs: 80, fat: 16 },
    { name: 'Steamed White Rice (side)', calories: 380, protein: 7, carbs: 86, fat: 0 },
    { name: 'Mixed Veggies (side)', calories: 90, protein: 4, carbs: 14, fat: 3 },
    { name: 'Super Greens (side)', calories: 90, protein: 6, carbs: 10, fat: 3 },
  ],
  jerseymikes: [
    { name: 'Turkey & Provolone #6 (regular)', calories: 558, protein: 40, carbs: 60, fat: 16 },
    { name: 'Club Supreme #13 (regular)', calories: 648, protein: 42, carbs: 60, fat: 24 },
    { name: 'Grilled Chicken Philly (regular)', calories: 620, protein: 44, carbs: 64, fat: 18 },
    { name: 'Big Kahuna Chicken #55 (regular)', calories: 690, protein: 46, carbs: 64, fat: 24 },
    { name: 'Chicken Bacon Ranch (regular)', calories: 720, protein: 48, carbs: 62, fat: 28 },
    { name: 'Tuna Fish (regular)', calories: 640, protein: 22, carbs: 60, fat: 36 },
    { name: 'Veggie Sub (regular)', calories: 460, protein: 18, carbs: 62, fat: 14 },
    { name: 'Rosemary Parmesan Bowl - Turkey', calories: 360, protein: 38, carbs: 20, fat: 14 },
  ],
  wholefoods: [
    { name: 'Rotisserie Chicken (4oz)', calories: 200, protein: 28, carbs: 0, fat: 10 },
    { name: 'Salmon Fillet (6oz)', calories: 250, protein: 34, carbs: 0, fat: 12 },
    { name: 'Quinoa Salad (1 cup)', calories: 320, protein: 9, carbs: 42, fat: 14 },
    { name: 'Lentil Soup (1 cup)', calories: 180, protein: 12, carbs: 28, fat: 3 },
    { name: 'Grilled Vegetables (1 cup)', calories: 120, protein: 3, carbs: 18, fat: 5 },
    { name: 'Brown Rice (1 cup cooked)', calories: 215, protein: 5, carbs: 45, fat: 2 },
    { name: 'Greek Salad (1 cup)', calories: 150, protein: 4, carbs: 8, fat: 12 },
    { name: 'Chicken Tikka Masala (serving)', calories: 380, protein: 28, carbs: 22, fat: 18 },
    { name: 'Edamame (1 cup)', calories: 189, protein: 17, carbs: 15, fat: 8 },
    { name: 'Sushi Roll - California (8pc)', calories: 380, protein: 10, carbs: 60, fat: 11 },
  ],
  traderjoes: [
    { name: 'Mandarin Orange Chicken (serving)', calories: 310, protein: 14, carbs: 42, fat: 10 },
    { name: 'Palak Paneer (half pack)', calories: 260, protein: 14, carbs: 18, fat: 14 },
    { name: 'Indian Fare Channa Masala', calories: 190, protein: 7, carbs: 34, fat: 4 },
    { name: 'Chicken Tikka Masala (half pack)', calories: 300, protein: 24, carbs: 20, fat: 12 },
    { name: 'Organic Riced Cauliflower (1 cup)', calories: 25, protein: 2, carbs: 5, fat: 0 },
    { name: 'Multigrain Bread (2 slices)', calories: 140, protein: 6, carbs: 28, fat: 2 },
    { name: 'Greek Style Yogurt (5.3oz)', calories: 90, protein: 15, carbs: 5, fat: 0.5 },
    { name: 'Almond Butter (2 tbsp)', calories: 190, protein: 7, carbs: 7, fat: 16 },
    { name: 'Reduced Guilt Mac & Cheese', calories: 340, protein: 14, carbs: 50, fat: 10 },
    { name: 'Egg White Salad (serving)', calories: 130, protein: 14, carbs: 6, fat: 6 },
  ],
  snacksbars: [
    { name: 'Quest Bar - Chocolate Chip Cookie Dough', calories: 190, protein: 21, carbs: 25, fat: 7 },
    { name: 'Quest Bar - White Chocolate Raspberry', calories: 180, protein: 20, carbs: 23, fat: 6 },
    { name: 'RXBAR Chocolate Sea Salt', calories: 210, protein: 12, carbs: 23, fat: 9 },
    { name: 'RXBAR Blueberry', calories: 210, protein: 12, carbs: 23, fat: 9 },
    { name: 'Barebells Milk Chocolate', calories: 200, protein: 20, carbs: 19, fat: 5 },
    { name: 'Barebells Cookies & Cream', calories: 199, protein: 20, carbs: 19, fat: 5 },
    { name: 'Fairlife Core Power 26g (vanilla)', calories: 230, protein: 26, carbs: 25, fat: 5 },
    { name: 'Fairlife Core Power 42g Elite (chocolate)', calories: 230, protein: 42, carbs: 14, fat: 5 },
    { name: 'Ghost Whey (1 scoop, vanilla)', calories: 130, protein: 25, carbs: 4, fat: 2 },
    { name: 'Kind Protein Bar - Dark Choc Nut', calories: 250, protein: 12, carbs: 24, fat: 13 },
    { name: 'Clif Bar - Chocolate Chip', calories: 250, protein: 9, carbs: 44, fat: 6 },
    { name: 'LaraBar - Apple Pie', calories: 190, protein: 4, carbs: 28, fat: 8 },
    { name: 'Perfect Bar - Chocolate Almond', calories: 350, protein: 17, carbs: 29, fat: 18 },
    { name: 'Premier Protein Shake (11.5oz)', calories: 160, protein: 30, carbs: 5, fat: 3 },
    { name: 'Muscle Milk Zero (11oz, vanilla)', calories: 100, protein: 20, carbs: 2, fat: 2 },
    { name: 'Siggi's Plain Skyr (5.3oz)', calories: 100, protein: 16, carbs: 8, fat: 0 },
    { name: 'Oikos Pro Vanilla (5.3oz)', calories: 120, protein: 20, carbs: 7, fat: 0 },
    { name: 'Chomps Beef Stick', calories: 90, protein: 9, carbs: 1, fat: 6 },
    { name: 'Epic Chicken Sriracha Bar', calories: 80, protein: 11, carbs: 4, fat: 2 },
    { name: 'Peanut Butter Toast (2 slices + 2tbsp PB)', calories: 410, protein: 14, carbs: 40, fat: 22 },
  ],
};

/**
 * All restaurant names with display labels
 */
export const RESTAURANT_NAMES = {
  chipotle: 'Chipotle',
  mcdonalds: "McDonald's",
  subway: 'Subway',
  chickfila: 'Chick-fil-A',
  sweetgreen: 'Sweetgreen',
  panera: 'Panera Bread',
  shakeshack: 'Shake Shack',
  starbucks: 'Starbucks',
  cava: 'Cava',
  pandaexpress: 'Panda Express',
  jerseymikes: "Jersey Mike's",
  wholefoods: 'Whole Foods',
  traderjoes: "Trader Joe's",
  snacksbars: 'Protein Bars & Snacks',
};

/**
 * Search across all restaurants
 */
export const searchRestaurants = (query) => {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  const results = [];
  for (const [restaurant, items] of Object.entries(RESTAURANT_MENUS)) {
    for (const item of items) {
      if (item.name.toLowerCase().includes(q)) {
        results.push({ ...item, restaurant, restaurantName: RESTAURANT_NAMES[restaurant] || restaurant });
      }
    }
  }
  return results.slice(0, 30);
};
